# Generated by Django 6.0.7 on 2026-08-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synola', '0002_conversationsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsummary',
            name='last_summarized_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='synola.message'),
        ),
    ]
