# Generated by Django 6.0.7 on 2026-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synola', '0003_conversationsummary_last_summarized_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('sha_256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('context_length', models.IntegerField(default=4096)),
                ('installed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
